import * as Icons from "lucide-react";

export const iconMap: Record<string, Icons.LucideIcon> = {
  reports: Icons.ClipboardMinus,
  management: Icons.LaptopMinimalCheck,
  user: Icons.UserRoundCog,
  userCheck: Icons.UserCheck,
  lock: Icons.KeyRound,
  report1: Icons.ClipboardMinus,
  report2: Icons.BookCheck,
  report3: Icons.Book,
  report4: Icons.BookAudio,
  report5: Icons.BookText,
  report6: Icons.BookA,
  home: Icons.House,
  id: Icons.PanelRightClose,
  info: Icons.BookType,
  status: Icons.CheckCheck,
  department1: Icons.Warehouse,
  department2: Icons.HousePlus,
  time1: Icons.ClockArrowUp,
  time2: Icons.ClockFading,
  question: Icons.BadgeQuestionMark,
  money: Icons.CircleDollarSign,
  bookmark: Icons.Bookmark,
  bookmarkCheck: Icons.BookmarkCheck,
  bookmarkPlus: Icons.BookmarkPlus,
  bookmarkMinus: Icons.BookmarkMinus,
  bookmarkX: Icons.BookmarkX,
  filePenLine: Icons.FilePenLine,
};
